application:
  title: "Alien Supremacy"
  version: 0.1
  formatted-version: v0.1 Alpha

server:
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true 
      jakarta:
        persistence:
          sharedCache:
            mode: ALL # https://github.com/spring-projects/spring-data-jpa/issues/2717
  datasource:
    #driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://sql204.epizy.com:3306/epiz_33652975_zoosevilla
    #username: epiz_33652975
    #password: 8k9ooBquBaq2
    
    platform: postgres
    url: jdbc:postgresql://dpg-ch421eb3cv21aod8bf00-a.frankfurt-postgres.render.com/alien_supremacy
    username: alien_supremacy_admin
    password: LIJJTKn0aP4Ye4KYZB0CF3nEpjjvOX0k
    driverClassName: org.postgresql.Driver
    
    #driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #username: root
    #password: rootroot
  thymeleaf:
    check-template-location: false